# Generated by Django 6.0 on 2025-12-06 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_skill_job_required_skills_skillsubmission'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='is_skill_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='skill_assessment_submission',
            field=models.FileField(blank=True, null=True, upload_to='assessments/'),
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='skills',
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='skills',
            field=models.ManyToManyField(blank=True, related_name='students', to='myapp.skill'),
        ),
    ]
