# Generated by Django 6.0 on 2025-12-18 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_siteupdate_remove_application_cover_letter_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='is_id_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='school_id_image',
            field=models.ImageField(blank=True, null=True, upload_to='student_ids/'),
        ),
    ]
