# Generated by Django 6.0 on 2025-12-18 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_studentprofile_is_id_verified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteupdate',
            name='audience',
            field=models.CharField(choices=[('all', 'All Users'), ('student', 'Students Only'), ('client', 'Clients Only')], default='all', max_length=10),
        ),
    ]
