# Generated by Django 6.0 on 2025-12-08 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_studentprofile_is_skill_verified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='skill',
            name='icon_class',
            field=models.CharField(default='bi-star-fill', help_text='Bootstrap icon class', max_length=50),
        ),
    ]
