# Generated by Django 6.0 on 2025-12-18 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_siteupdate_audience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteupdate',
            name='audience',
            field=models.CharField(choices=[('all', 'All Users'), ('student', 'Students Only'), ('client', 'Clients Only'), ('donor', 'Donors Only')], default='all', max_length=10),
        ),
    ]
