# Generated by Django 6.0 on 2025-12-20 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_siteupdate_audience'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='id_rejection_reason',
            field=models.TextField(blank=True, help_text='Reason for rejecting the ID', null=True),
        ),
    ]
