# Generated by Django 6.0 on 2025-12-22 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_studentprofile_id_rejection_reason'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_verified',
            new_name='is_account_verified',
        ),
    ]
